/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carihotelyuk;

import java.awt.FlowLayout;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Array;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultButtonModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

/**
 *
 * @author Katon Gilang
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        //tampilRatingTertinggi();
        //tampilTermurah();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        tfSearch = new javax.swing.JTextField();
        jButtonGo = new javax.swing.JButton();
        lblAdmin = new javax.swing.JLabel();
        panelGambar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelGambar1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        menBarHome = new javax.swing.JMenuBar();
        menuLihat = new javax.swing.JMenu();
        menuBeranda = new javax.swing.JMenuItem();
        itemDaftarHotel = new javax.swing.JMenuItem();
        itemReview = new javax.swing.JMenuItem();
        itemDaftarUser = new javax.swing.JMenuItem();
        itemDaftarFavorite = new javax.swing.JMenuItem();
        menuModerasi = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuModerasiGambar = new javax.swing.JMenuItem();
        asa = new javax.swing.JMenu();
        itemDaftar = new javax.swing.JMenuItem();
        itemMasuk = new javax.swing.JMenuItem();
        itemGantiPassword = new javax.swing.JMenuItem();
        menuKeluar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Cari         :");

        tfSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButtonGo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonGo.setText("GO !");
        jButtonGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGoActionPerformed(evt);
            }
        });

        lblAdmin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAdmin.setText("SELAMAT DATANG DI BERANDA ADMIN, SEMOGA HARI ANDA MENYENANGKAN");

        javax.swing.GroupLayout panelGambarLayout = new javax.swing.GroupLayout(panelGambar);
        panelGambar.setLayout(panelGambarLayout);
        panelGambarLayout.setHorizontalGroup(
            panelGambarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 673, Short.MAX_VALUE)
        );
        panelGambarLayout.setVerticalGroup(
            panelGambarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 254, Short.MAX_VALUE)
        );

        jLabel1.setText("HOTEL RATING TERTINGGI   :");

        javax.swing.GroupLayout panelGambar1Layout = new javax.swing.GroupLayout(panelGambar1);
        panelGambar1.setLayout(panelGambar1Layout);
        panelGambar1Layout.setHorizontalGroup(
            panelGambar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelGambar1Layout.setVerticalGroup(
            panelGambar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 232, Short.MAX_VALUE)
        );

        jLabel3.setText("HOTEL RATING TERMURAH   :");

        menBarHome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        menuLihat.setText("Lihat");

        menuBeranda.setText("Beranda");
        menuBeranda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBerandaActionPerformed(evt);
            }
        });
        menuLihat.add(menuBeranda);

        itemDaftarHotel.setText("Daftar Hotel");
        itemDaftarHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDaftarHotelActionPerformed(evt);
            }
        });
        menuLihat.add(itemDaftarHotel);

        itemReview.setText("Daftar Review");
        itemReview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemReviewActionPerformed(evt);
            }
        });
        menuLihat.add(itemReview);

        itemDaftarUser.setText("Daftar User");
        itemDaftarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDaftarUserActionPerformed(evt);
            }
        });
        menuLihat.add(itemDaftarUser);

        itemDaftarFavorite.setText("Daftar Favorite");
        itemDaftarFavorite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDaftarFavoriteActionPerformed(evt);
            }
        });
        menuLihat.add(itemDaftarFavorite);

        menBarHome.add(menuLihat);

        menuModerasi.setText("Moderasi");

        jMenuItem1.setText("No Tlp");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuModerasi.add(jMenuItem1);

        menuModerasiGambar.setText("Gambar");
        menuModerasiGambar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuModerasiGambarActionPerformed(evt);
            }
        });
        menuModerasi.add(menuModerasiGambar);

        menBarHome.add(menuModerasi);

        asa.setText("User");
        asa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asaActionPerformed(evt);
            }
        });
        asa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                asaKeyPressed(evt);
            }
        });

        itemDaftar.setText("Daftar");
        itemDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDaftarActionPerformed(evt);
            }
        });
        asa.add(itemDaftar);

        itemMasuk.setText("Masuk");
        itemMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMasukActionPerformed(evt);
            }
        });
        asa.add(itemMasuk);

        itemGantiPassword.setText("Ubah Password");
        itemGantiPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGantiPasswordActionPerformed(evt);
            }
        });
        asa.add(itemGantiPassword);

        menuKeluar.setText("Keluar");
        menuKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKeluarActionPerformed(evt);
            }
        });
        asa.add(menuKeluar);

        menBarHome.add(asa);

        setJMenuBar(menBarHome);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblAdmin)
                .addGap(46, 46, 46))
            .addComponent(panelGambar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelGambar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonGo))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelGambar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(panelGambar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void tampilRatingTertinggi(){
        String[] gambar= new String[3];
        String[] namaHotel= new String[3];
        int[] idHotel = new int[3];
        int count = 0;
        panelGambar.setLayout(new FlowLayout(FlowLayout.CENTER));
        try{
        
        String sql="SELECT g.id_gambar,g.id_hotel,g.status_moderasi,g.path_gambar,g.gambar_utama, h.id_hotel,h.nama_hotel, h.rating_hotel from gambar g, hotel h WHERE g.id_hotel=h.id_hotel AND g.status_moderasi='approved' AND g.gambar_utama='ya' ORDER BY h.rating_hotel DESC LIMIT 3";
        Connection con=ModuleDB.connectDB();
        Statement stmt=con.createStatement();
        ResultSet result=stmt.executeQuery(sql);
            while(result.next() && count<3){
                gambar[count]=result.getString("path_gambar");
                idHotel[count]=result.getInt("id_hotel");
                namaHotel[count]=result.getString("nama_hotel");
                count++;
            }
        }
        catch(SQLException e){
            showMessageDialog(null,e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
        
        for(int i=0;i<3;i++){
            final int c = i;
            BufferedImage img= null;
            try{
                img = ImageIO.read(new File(gambar[i]));
            } catch(IOException e){
                showMessageDialog(null,e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
            }
            Image newImg = img.getScaledInstance(145, 210, Image.SCALE_SMOOTH);
            ImageIcon imgIcon = new ImageIcon(newImg);
           
            panelGambar.add(new JButton(namaHotel[i],imgIcon){
                {
                    setSize(145, 210);
                    setMaximumSize(getSize());
                    setVerticalTextPosition(SwingConstants.BOTTOM);
                    setHorizontalTextPosition(SwingConstants.CENTER);
                    addActionListener(new java.awt.event.ActionListener(){
                        public void actionPerformed(java.awt.event.ActionEvent evt){
                            btnTampilActionPerformed(evt, idHotel[c]);
                        }
                    });
                }
            });
            System.out.println(gambar[i]);
        }
    }
    
    public void tampilTermurah(){
        String[] gambar= new String[3];
        String[] namaHotel= new String[3];
        int[] idHotel = new int[3];
        int count = 0;
        panelGambar1.setLayout(new FlowLayout(FlowLayout.CENTER));
        try{
        
        String sql="SELECT g.id_gambar,g.id_hotel,g.status_moderasi,g.path_gambar,g.gambar_utama, h.id_hotel,h.nama_hotel, h.rating_hotel from gambar g, hotel h WHERE g.id_hotel=h.id_hotel AND g.status_moderasi='approved' AND g.gambar_utama='ya' ORDER BY h.starting_price ASC LIMIT 3";
        Connection con=ModuleDB.connectDB();
        Statement stmt=con.createStatement();
        ResultSet result=stmt.executeQuery(sql);
            while(result.next() && count<3){
                gambar[count]=result.getString("path_gambar");
                idHotel[count]=result.getInt("id_hotel");
                namaHotel[count]=result.getString("nama_hotel");
                count++;
            }
        }
        catch(SQLException e){
            showMessageDialog(null,e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
        
        for(int i=0;i<3;i++){
            final int c = i;
            BufferedImage img= null;
            try{
                img = ImageIO.read(new File(gambar[i]));
            } catch(IOException e){
                showMessageDialog(null,e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
            }
            Image newImg = img.getScaledInstance(145, 210, Image.SCALE_SMOOTH);
            ImageIcon imgIcon = new ImageIcon(newImg);
           
            panelGambar1.add(new JButton(namaHotel[i],imgIcon){
                {
                    setSize(145, 210);
                    setMaximumSize(getSize());
                    setVerticalTextPosition(SwingConstants.BOTTOM);
                    setHorizontalTextPosition(SwingConstants.CENTER);
                    addActionListener(new java.awt.event.ActionListener(){
                        public void actionPerformed(java.awt.event.ActionEvent evt){
                            btnTampilActionPerformed(evt, idHotel[c]);
                        }
                    });
                }
            });
            System.out.println(gambar[i]);
        }
    }
    
    private void btnTampilActionPerformed(java.awt.event.ActionEvent evt, int i){
        System.out.println(i);//olih id
        LihatDetail er=new LihatDetail(this,i);
        er.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        er.setVisible(true);
        
    }
    private void jButtonGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGoActionPerformed
        String keyword=tfSearch.getText();
        
        if(!keyword.isEmpty()){
        HasilPencarian h=new HasilPencarian(this,keyword);
        h.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        h.setVisible(true);
        this.dispose();
        }
        else showMessageDialog(null,"Field harus diisi!");
    }//GEN-LAST:event_jButtonGoActionPerformed

    
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setLocationRelativeTo(null);
        if("guest".equals(ModuleDB.level)){ //kalo user guest
            lblAdmin.setVisible(false);
            menuModerasi.setVisible(false);
            itemDaftarHotel.setVisible(false);
            itemReview.setVisible(false);
            itemDaftarUser.setVisible(false);
            itemMasuk.setVisible(false);
            itemDaftar.setVisible(false);
            asa.setText(ModuleDB.nama_lengkap);
        } 
        else if(ModuleDB.level==null){ //kalo user biasa
            lblAdmin.setVisible(false);
            menuKeluar.setVisible(false);
            menuModerasi.setVisible(false);
            itemDaftarHotel.setVisible(false);
            itemReview.setVisible(false);
            itemDaftarUser.setVisible(false);
            itemGantiPassword.setVisible(false);
            itemDaftarFavorite.setVisible(false);
        }
        else{ //kalo admin
            itemMasuk.setVisible(false);
            itemDaftar.setVisible(false);
            itemGantiPassword.setVisible(false);
            itemDaftarFavorite.setVisible(false);
            asa.setText(ModuleDB.nama_lengkap);
        }
    }//GEN-LAST:event_formWindowOpened

    private void menuBerandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBerandaActionPerformed
        new Home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuBerandaActionPerformed

    private void itemDaftarHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDaftarHotelActionPerformed
        DaftarHotel d=new DaftarHotel();
        d.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        d.setVisible(true);
    }//GEN-LAST:event_itemDaftarHotelActionPerformed

    private void menuKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKeluarActionPerformed
        ModuleDB.username=null;
        ModuleDB.level=null;
        ModuleDB.id_user=0;
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuKeluarActionPerformed

    private void asaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asaActionPerformed

    }//GEN-LAST:event_asaActionPerformed

    private void asaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_asaKeyPressed

    }//GEN-LAST:event_asaKeyPressed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        ModerasiNoTlp m=new ModerasiNoTlp();
        m.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        m.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void itemDaftarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDaftarUserActionPerformed
        DaftarUser m=new DaftarUser();
        m.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        m.setVisible(true);
    }//GEN-LAST:event_itemDaftarUserActionPerformed

    private void menuModerasiGambarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuModerasiGambarActionPerformed
        ModerasiGambar m=new ModerasiGambar();
        m.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        m.setVisible(true);
    }//GEN-LAST:event_menuModerasiGambarActionPerformed

    private void itemDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDaftarActionPerformed
        new Register().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_itemDaftarActionPerformed

    private void itemMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMasukActionPerformed
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_itemMasukActionPerformed

    private void itemGantiPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGantiPasswordActionPerformed
        UbahPassword m=new UbahPassword();
        m.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        m.setVisible(true);
    }//GEN-LAST:event_itemGantiPasswordActionPerformed

    private void itemReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemReviewActionPerformed
        DaftarReview m=new DaftarReview();
        m.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        m.setVisible(true);
    }//GEN-LAST:event_itemReviewActionPerformed

    private void itemDaftarFavoriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDaftarFavoriteActionPerformed
        DaftarFavorite m=new DaftarFavorite();
        m.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        m.setVisible(true);
    }//GEN-LAST:event_itemDaftarFavoriteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu asa;
    private javax.swing.JMenuItem itemDaftar;
    private javax.swing.JMenuItem itemDaftarFavorite;
    private javax.swing.JMenuItem itemDaftarHotel;
    private javax.swing.JMenuItem itemDaftarUser;
    private javax.swing.JMenuItem itemGantiPassword;
    private javax.swing.JMenuItem itemMasuk;
    private javax.swing.JMenuItem itemReview;
    private javax.swing.JButton jButtonGo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lblAdmin;
    private javax.swing.JMenuBar menBarHome;
    private javax.swing.JMenuItem menuBeranda;
    private javax.swing.JMenuItem menuKeluar;
    private javax.swing.JMenu menuLihat;
    private javax.swing.JMenu menuModerasi;
    private javax.swing.JMenuItem menuModerasiGambar;
    private javax.swing.JPanel panelGambar;
    private javax.swing.JPanel panelGambar1;
    private javax.swing.JTextField tfSearch;
    // End of variables declaration//GEN-END:variables
}
