/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carihotelyuk;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;
import static javax.swing.JOptionPane.showMessageDialog;
import static javax.swing.JOptionPane.showMessageDialog;
import static javax.swing.JOptionPane.showMessageDialog;
import static javax.swing.JOptionPane.showMessageDialog;
import static javax.swing.JOptionPane.showMessageDialog;
import static javax.swing.JOptionPane.showMessageDialog;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author Katon Gilang
 */
public class LihatDetailHotelPunyaAdmin extends javax.swing.JFrame {

    /**
     * Creates new form LihatDetailHotelPunyaAdmin
     */
    DaftarHotel formDaftarHotel;
    private int idHotel;
    public LihatDetailHotelPunyaAdmin() {
        initComponents();
    }
    public LihatDetailHotelPunyaAdmin(DaftarHotel formDaftarHotel, int idHotel, String namaHotel) {
        initComponents();
        this.idHotel=idHotel;
        this.formDaftarHotel=formDaftarHotel;
        lblNamaHotel.setText(namaHotel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jtabRuangan = new javax.swing.JTable();
        lblNamaHotel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnDeleteRuangan = new javax.swing.JButton();
        buttonTambahRuang = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtabDaftarNoTlp = new javax.swing.JTable();
        btnDeleteNoTlp = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        buttonTambahNoTlp = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtabGambar = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnDeleteGambar = new javax.swing.JButton();
        btnTambahGambar = new javax.swing.JButton();
        btnUbahRuangan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jtabRuangan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Ruangan", "Nama Hotel", "Kelas Ruangan", "Kapasitas", "Harga_Per_Malam"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jtabRuangan);

        lblNamaHotel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNamaHotel.setText("NAMA HOTELNYA");

        jLabel1.setText("Daftar Ruangan ");

        btnDeleteRuangan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDeleteRuangan.setText("Delete");
        btnDeleteRuangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteRuanganActionPerformed(evt);
            }
        });

        buttonTambahRuang.setText("Tambah Ruangan");
        buttonTambahRuang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahRuangActionPerformed(evt);
            }
        });

        jtabDaftarNoTlp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No Tlp", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtabDaftarNoTlp);

        btnDeleteNoTlp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDeleteNoTlp.setText("Delete");
        btnDeleteNoTlp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteNoTlpActionPerformed(evt);
            }
        });

        jLabel2.setText("Daftar No Tlp");

        buttonTambahNoTlp.setText("Tambah No Tlp");
        buttonTambahNoTlp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahNoTlpActionPerformed(evt);
            }
        });

        jtabGambar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Path Gambar", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jtabGambar);

        jLabel3.setText("Daftar Path Gambar");

        btnDeleteGambar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDeleteGambar.setText("Delete");
        btnDeleteGambar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteGambarActionPerformed(evt);
            }
        });

        btnTambahGambar.setText("Tambah Gambar");
        btnTambahGambar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahGambarActionPerformed(evt);
            }
        });

        btnUbahRuangan.setText("Ubah");
        btnUbahRuangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahRuanganActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNamaHotel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(buttonTambahRuang, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnUbahRuangan)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnDeleteRuangan))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(buttonTambahNoTlp, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(41, 41, 41)
                                    .addComponent(btnDeleteNoTlp))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTambahGambar, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDeleteGambar))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblNamaHotel)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonTambahNoTlp, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(btnDeleteNoTlp)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDeleteRuangan)
                        .addComponent(btnDeleteGambar)
                        .addComponent(btnTambahGambar)
                        .addComponent(btnUbahRuangan))
                    .addComponent(buttonTambahRuang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(129, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void tampilanRuangan(){
        int rowIdx=jtabRuangan.getSelectedRow();
        //int idHotelLihatRuangan=Integer.parseInt(jtabRuangan.getValueAt(rowIdx,0).toString());
        try{
            String sql="SELECT h.id_hotel, h.nama_hotel,r.id_hotel,r.kelas_ruang,r.id_ruang,r.kapasitas,r.harga_per_malam FROM hotel h, ruangan r WHERE r.id_hotel=h.id_hotel AND h.id_hotel="+idHotel;
            Connection con=ModuleDB.connectDB();
            Statement stmt=con.createStatement();
            ResultSet result=stmt.executeQuery(sql);
            DefaultTableModel model=(DefaultTableModel)jtabRuangan.getModel();
            model.setRowCount(0);
            while(result.next()){
                Vector row=new Vector();
                row.add(result.getString("id_ruang"));
                row.add(result.getString("nama_hotel"));
                row.add(result.getString("kelas_ruang"));
                row.add(result.getString("kapasitas"));
                row.add(result.getInt("harga_per_malam"));
                model.addRow(row);
            }
            con.close();
            jtabRuangan.setModel(model);
        }
        catch(SQLException e){
            showMessageDialog(null,e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
    }
    public void tampilanNoTlp(){
        int rowIdx=jtabDaftarNoTlp.getSelectedRow();
       
        try{
            String sql="SELECT h.id_hotel,n.no_telp,n.status_moderasi FROM hotel h, no_telp n WHERE n.id_hotel=h.id_hotel AND n.status_moderasi='approved' AND h.id_hotel="+idHotel;
            Connection con=ModuleDB.connectDB();
            Statement stmt=con.createStatement();
            ResultSet result=stmt.executeQuery(sql);
            DefaultTableModel model=(DefaultTableModel)jtabDaftarNoTlp.getModel();
            model.setRowCount(0);
            while(result.next()){
                Vector row=new Vector();
                row.add(result.getString("no_telp"));
                row.add(result.getString("status_moderasi"));
                model.addRow(row);
            }
            con.close();
            jtabDaftarNoTlp.setModel(model);
        }
        catch(SQLException e){
            showMessageDialog(null,e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
    }
    public void tampilanGambar(){
        int rowIdx=jtabGambar.getSelectedRow();
       
        try{
            String sql="SELECT h.id_hotel,g.id_gambar, g.id_hotel,g.path_gambar,g.status_moderasi FROM hotel h, gambar g WHERE g.id_hotel=h.id_hotel AND g.status_moderasi='approved' AND h.id_hotel="+idHotel;
            Connection con=ModuleDB.connectDB();
            Statement stmt=con.createStatement();
            ResultSet result=stmt.executeQuery(sql);
            DefaultTableModel model=(DefaultTableModel)jtabGambar.getModel();
            model.setRowCount(0);
            while(result.next()){
                Vector row=new Vector();
                row.add(result.getString("id_gambar"));
                row.add(result.getString("path_gambar"));
                row.add(result.getString("status_moderasi"));
                model.addRow(row);
            }
            con.close();
            jtabGambar.setModel(model);
        }
        catch(SQLException e){
            showMessageDialog(null,e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setLocationRelativeTo(null);
        tampilanRuangan();
        tampilanNoTlp();
        tampilanGambar();
    }//GEN-LAST:event_formWindowOpened

    private void btnDeleteRuanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteRuanganActionPerformed
        int dialogResult=JOptionPane.showOptionDialog(null,"Apakah anda yakin menghapus ruangan hotel ini?","Konfirmasi Hapus Data Hotel",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,null,null);
        if(dialogResult==JOptionPane.YES_OPTION){
            int rowIdx=jtabRuangan.getSelectedRow();
            int idRuangan=Integer.parseInt(jtabRuangan.getValueAt(rowIdx,0).toString());
            String sql="DELETE FROM ruangan WHERE id_ruang="+idRuangan;
            try{
                Connection con=ModuleDB.connectDB();
                Statement stmt=con.createStatement();
                stmt.executeUpdate(sql);
                showMessageDialog(null,"Ruangan berhasil dihapus!");
                tampilanRuangan();
            }
            catch(SQLException e){
                showMessageDialog(null,e.getMessage());
            }
        }
    }//GEN-LAST:event_btnDeleteRuanganActionPerformed

    private void buttonTambahRuangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahRuangActionPerformed
        TambahRuangan formRuangan=new TambahRuangan(this,idHotel);
        formRuangan.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        formRuangan.setVisible(true);
    }//GEN-LAST:event_buttonTambahRuangActionPerformed

    private void btnDeleteNoTlpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteNoTlpActionPerformed
        int dialogResult=JOptionPane.showOptionDialog(null,"Apakah anda yakin menghapus no tlp hotel ini?","Konfirmasi Hapus no tlp",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,null,null);
        if(dialogResult==JOptionPane.YES_OPTION){
            int rowIdx=jtabDaftarNoTlp.getSelectedRow();
            int noTlp=Integer.parseInt(jtabDaftarNoTlp.getValueAt(rowIdx,0).toString());
            String sql="DELETE FROM no_telp WHERE no_telp="+noTlp;
            try{
                Connection con=ModuleDB.connectDB();
                Statement stmt=con.createStatement();
                stmt.executeUpdate(sql);
                showMessageDialog(null,"No Tlp berhasil dihapus!");
                tampilanNoTlp();
            }
            catch(SQLException e){
                showMessageDialog(null,e.getMessage());
            }
        }
    }//GEN-LAST:event_btnDeleteNoTlpActionPerformed

    private void buttonTambahNoTlpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahNoTlpActionPerformed
        TambahNoTlp c=new TambahNoTlp(this,idHotel);
        c.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        c.setVisible(true);
    }//GEN-LAST:event_buttonTambahNoTlpActionPerformed

    private void btnDeleteGambarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteGambarActionPerformed
        int dialogResult=JOptionPane.showOptionDialog(null,"Apakah anda yakin menghapus path gambar hotel ini?","Konfirmasi Hapus path gambar",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,null,null);
        if(dialogResult==JOptionPane.YES_OPTION){
            int rowIdx=jtabGambar.getSelectedRow();
            int idGambar=Integer.parseInt(jtabGambar.getValueAt(rowIdx,0).toString());
            String sql="DELETE FROM gambar WHERE id_gambar="+idGambar;
            try{
                Connection con=ModuleDB.connectDB();
                Statement stmt=con.createStatement();
                stmt.executeUpdate(sql);
                showMessageDialog(null,"Path Gambar berhasil dihapus!");
                tampilanGambar();
            }
            catch(SQLException e){
                showMessageDialog(null,e.getMessage());
            }
        }
    }//GEN-LAST:event_btnDeleteGambarActionPerformed

    private void btnTambahGambarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahGambarActionPerformed
        TambahGambar g=new TambahGambar(this,idHotel);
        g.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        g.setVisible(true);
    }//GEN-LAST:event_btnTambahGambarActionPerformed

    private void btnUbahRuanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahRuanganActionPerformed
        int rowIdx=jtabRuangan.getSelectedRow();
        int idRuangan=Integer.parseInt(jtabRuangan.getValueAt(rowIdx,0).toString());
        String namaHotel=jtabRuangan.getValueAt(rowIdx,1).toString();
        String kelas=jtabRuangan.getValueAt(rowIdx,2).toString();
        String kapasitas=jtabRuangan.getValueAt(rowIdx,3).toString();
        int hargaPerMalam=Integer.parseInt(jtabRuangan.getValueAt(rowIdx,4).toString());
        
        
        EditRuangan er=new EditRuangan(this,idRuangan,idHotel,namaHotel,kelas,kapasitas,hargaPerMalam);
        er.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        er.setVisible(true);
    }//GEN-LAST:event_btnUbahRuanganActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LihatDetailHotelPunyaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LihatDetailHotelPunyaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LihatDetailHotelPunyaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LihatDetailHotelPunyaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LihatDetailHotelPunyaAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteGambar;
    private javax.swing.JButton btnDeleteNoTlp;
    private javax.swing.JButton btnDeleteRuangan;
    private javax.swing.JButton btnTambahGambar;
    private javax.swing.JButton btnUbahRuangan;
    private javax.swing.JButton buttonTambahNoTlp;
    private javax.swing.JButton buttonTambahRuang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jtabDaftarNoTlp;
    private javax.swing.JTable jtabGambar;
    private javax.swing.JTable jtabRuangan;
    private javax.swing.JLabel lblNamaHotel;
    // End of variables declaration//GEN-END:variables
}
