/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carihotelyuk;

import java.awt.FlowLayout;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.SwingConstants;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author Katon Gilang
 */
public class LihatDetail extends javax.swing.JFrame {
    Image image;
    private int idHotel;
    HasilPencarian h;
    Home hm;
    public LihatDetail() {
        initComponents();
    }
    public LihatDetail(HasilPencarian h, int idHotel){
        initComponents();
        this.idHotel=idHotel;
        this.h=h;
        tampil(idHotel);
    }
    public LihatDetail(Home hm, int idHotel){
        initComponents();
        this.idHotel=idHotel;
        tampil(idHotel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        alamat = new javax.swing.JLabel();
        tingkatBintang = new javax.swing.JLabel();
        nmHotel = new javax.swing.JLabel();
        fasilitas = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        totalRating = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        startingPrice = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panelNotifRanting = new javax.swing.JPanel();
        notifnya = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        notif = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtabNoTlp = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        PanelTlp = new javax.swing.JPanel();
        btnTambahNoTlo = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        tfNoHp = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtabRuangan = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        panelRating = new javax.swing.JPanel();
        btnBuatRatingg = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        cbKebersihan = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cbKenyamanan = new javax.swing.JComboBox<>();
        cbPelayanan = new javax.swing.JComboBox<>();
        cbRuangan = new javax.swing.JComboBox<>();
        cbMakanan = new javax.swing.JComboBox<>();
        panelNotifReview = new javax.swing.JPanel();
        notifnya1 = new javax.swing.JLabel();
        panelReview = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtIsiReview = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        btnBuatReview = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        detailGambar = new javax.swing.JPanel();
        panelTambahGambar = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtFoto = new javax.swing.JTextField();
        btnBrowse = new javax.swing.JButton();
        btnTambahGbr = new javax.swing.JButton();
        panelGambar1 = new carihotelyuk.PanelGambar();
        jScrollPane6 = new javax.swing.JScrollPane();
        jtabTampilReview = new javax.swing.JTable();
        btnTambahFavorite = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        alamat.setText("b");

        tingkatBintang.setText("c");

        nmHotel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nmHotel.setText("a");

        fasilitas.setText("e");

        jLabel1.setText("Nama Hotel                    :");

        jLabel20.setText("TOTAL RATING HOTEL   :");

        jLabel9.setText("Rp ");

        totalRating.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        totalRating.setText("f");

        jLabel2.setText("Alamat                           :");

        startingPrice.setText("d");

        jLabel4.setText("Starting Price                 :");

        jLabel3.setText("Tingkat Bintang              :");

        jLabel5.setText("Fasilitas                          :");

        panelNotifRanting.setBorder(javax.swing.BorderFactory.createTitledBorder("Form Rating"));

        notifnya.setText("Anda Sudah Memberi Rating terhadap hotel ini");

        javax.swing.GroupLayout panelNotifRantingLayout = new javax.swing.GroupLayout(panelNotifRanting);
        panelNotifRanting.setLayout(panelNotifRantingLayout);
        panelNotifRantingLayout.setHorizontalGroup(
            panelNotifRantingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNotifRantingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(notifnya, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        panelNotifRantingLayout.setVerticalGroup(
            panelNotifRantingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNotifRantingLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(notifnya)
                .addContainerGap())
        );

        jLabel11.setText("-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");

        notif.setText("***Daftar sebagai User Guest untuk menambahkan No Tlp dan  Gambar ! dan memberikan review dan rating !");

        jLabel15.setText("Daftar Review terhadap Hotel ini");

        jtabNoTlp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No Tlp"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jtabNoTlp);

        jLabel7.setText("Daftar No Tlp");

        PanelTlp.setBorder(javax.swing.BorderFactory.createTitledBorder("Form Tambah No Tlp"));

        btnTambahNoTlo.setText("Tambah");
        btnTambahNoTlo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahNoTloActionPerformed(evt);
            }
        });

        jLabel13.setText("No Tlp         :");

        tfNoHp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNoHpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelTlpLayout = new javax.swing.GroupLayout(PanelTlp);
        PanelTlp.setLayout(PanelTlpLayout);
        PanelTlpLayout.setHorizontalGroup(
            PanelTlpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTlpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfNoHp, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTambahNoTlo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelTlpLayout.setVerticalGroup(
            PanelTlpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTlpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelTlpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tfNoHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambahNoTlo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtabRuangan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kelas Ruangan", "Kapasitas", "Harga Per Malam"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jtabRuangan);

        jLabel8.setText("Daftar Ruangan");

        panelRating.setBorder(javax.swing.BorderFactory.createTitledBorder("Form Rating"));

        btnBuatRatingg.setText("Ok");
        btnBuatRatingg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuatRatinggActionPerformed(evt);
            }
        });

        jLabel10.setText("Kebersihan            :");

        cbKebersihan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        jLabel16.setText("Kenyamanan         :");

        jLabel19.setText("Pelayanan              :");

        jLabel17.setText("Makanan                :");

        jLabel18.setText("Ruangan                :");

        cbKenyamanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        cbPelayanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        cbRuangan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        cbMakanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        javax.swing.GroupLayout panelRatingLayout = new javax.swing.GroupLayout(panelRating);
        panelRating.setLayout(panelRatingLayout);
        panelRatingLayout.setHorizontalGroup(
            panelRatingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRatingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRatingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRatingLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbKebersihan, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRatingLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbKenyamanan, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRatingLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbMakanan, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRatingLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRatingLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbPelayanan, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRatingLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBuatRatingg)
                .addContainerGap())
        );
        panelRatingLayout.setVerticalGroup(
            panelRatingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRatingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRatingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cbKebersihan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRatingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(cbKenyamanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRatingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(cbMakanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRatingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(cbRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRatingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(cbPelayanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(btnBuatRatingg)
                .addContainerGap())
        );

        panelNotifReview.setBorder(javax.swing.BorderFactory.createTitledBorder("Form Review"));

        notifnya1.setText("Anda Sudah Memberi Review terhadap hotel ini");

        javax.swing.GroupLayout panelNotifReviewLayout = new javax.swing.GroupLayout(panelNotifReview);
        panelNotifReview.setLayout(panelNotifReviewLayout);
        panelNotifReviewLayout.setHorizontalGroup(
            panelNotifReviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNotifReviewLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(notifnya1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelNotifReviewLayout.setVerticalGroup(
            panelNotifReviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNotifReviewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(notifnya1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelReview.setBorder(javax.swing.BorderFactory.createTitledBorder("Form Review"));

        txtIsiReview.setColumns(20);
        txtIsiReview.setRows(5);
        jScrollPane3.setViewportView(txtIsiReview);

        jLabel12.setText("Masukkan Review untuk Hotel ini");

        btnBuatReview.setText("Ok");
        btnBuatReview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuatReviewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelReviewLayout = new javax.swing.GroupLayout(panelReview);
        panelReview.setLayout(panelReviewLayout);
        panelReviewLayout.setHorizontalGroup(
            panelReviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReviewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelReviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBuatReview)
                    .addGroup(panelReviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelReviewLayout.setVerticalGroup(
            panelReviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReviewLayout.createSequentialGroup()
                .addComponent(jLabel12)
                .addGap(9, 9, 9)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuatReview))
        );

        javax.swing.GroupLayout detailGambarLayout = new javax.swing.GroupLayout(detailGambar);
        detailGambar.setLayout(detailGambarLayout);
        detailGambarLayout.setHorizontalGroup(
            detailGambarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1078, Short.MAX_VALUE)
        );
        detailGambarLayout.setVerticalGroup(
            detailGambarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 258, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(detailGambar);

        panelTambahGambar.setBorder(javax.swing.BorderFactory.createTitledBorder("Form Tambah Gambar"));

        jLabel14.setText("Gambar      :");

        txtFoto.setEditable(false);
        txtFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFotoActionPerformed(evt);
            }
        });

        btnBrowse.setText("...");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });

        btnTambahGbr.setText("Tambah");
        btnTambahGbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahGbrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGambar1Layout = new javax.swing.GroupLayout(panelGambar1);
        panelGambar1.setLayout(panelGambar1Layout);
        panelGambar1Layout.setHorizontalGroup(
            panelGambar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 89, Short.MAX_VALUE)
        );
        panelGambar1Layout.setVerticalGroup(
            panelGambar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 89, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelTambahGambarLayout = new javax.swing.GroupLayout(panelTambahGambar);
        panelTambahGambar.setLayout(panelTambahGambarLayout);
        panelTambahGambarLayout.setHorizontalGroup(
            panelTambahGambarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTambahGambarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(36, 36, 36)
                .addComponent(txtFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBrowse, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTambahGambarLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(panelGambar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTambahGbr)
                .addGap(21, 21, 21))
        );
        panelTambahGambarLayout.setVerticalGroup(
            panelTambahGambarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTambahGambarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTambahGambarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(btnBrowse)
                    .addComponent(txtFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelTambahGambarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTambahGambarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelGambar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTambahGambarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTambahGbr)
                        .addContainerGap())))
        );

        jtabTampilReview.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Reviewer", "Isi Review"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jtabTampilReview);

        btnTambahFavorite.setText("Tambahkan ke Favorite");
        btnTambahFavorite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahFavoriteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(panelTambahGambar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(totalRating))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel5))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(11, 11, 11)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(alamat)
                                                    .addComponent(nmHotel)
                                                    .addComponent(tingkatBintang)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(fasilitas))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(startingPrice))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(PanelTlp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 121, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane6)
                                    .addComponent(jLabel15))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(panelReview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(panelNotifRanting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(panelRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(panelNotifReview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 931, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnTambahFavorite, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(160, 160, 160)
                                .addComponent(notif)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(notif)
                    .addComponent(btnTambahFavorite, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nmHotel)
                        .addGap(18, 18, 18)
                        .addComponent(alamat)
                        .addGap(18, 18, 18)
                        .addComponent(tingkatBintang))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(startingPrice)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fasilitas)
                            .addComponent(jLabel5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(totalRating))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PanelTlp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelTambahGambar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(panelNotifReview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelReview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelNotifRanting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(panelRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jScrollPane4.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1085, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void tampil(int id){
        
        List<String> gambar= new ArrayList<String>();
        int count = 0;
        detailGambar.setLayout(new FlowLayout(FlowLayout.LEFT));
        
        try{     
        System.out.println(id);
        String sql="SELECT * from gambar WHERE id_hotel="+id;
        Connection con=ModuleDB.connectDB();
        Statement stmt=con.createStatement();
        ResultSet result=stmt.executeQuery(sql);
            while(result.next()){
                gambar.add(result.getString("path_gambar"));
                //System.out.println(result.getString("path_gambar"));//nggo ngetest
                count++;
            }
            
        }
        catch(SQLException e){
            showMessageDialog(null,e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
        
        for(String g:gambar){
            System.out.println(g);
            BufferedImage img= null;
            try{
                img = ImageIO.read(new File(g));
            } catch(IOException e){
                showMessageDialog(null,e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
            }
            Image newImg = img.getScaledInstance(145, 210, Image.SCALE_SMOOTH);
            ImageIcon imgIcon = new ImageIcon(newImg);
           
            detailGambar.add(new JButton("Blabla",imgIcon){
                {
                    setSize(145, 210);
                    setMaximumSize(getSize());
                    setVerticalTextPosition(SwingConstants.BOTTOM);
                    setHorizontalTextPosition(SwingConstants.CENTER);
                }
            });}
    }
    
    private void tampilDetail(){
        try{
            String sqlHotel= "SELECT * FROM hotel WHERE id_hotel="+idHotel;
            Connection con=ModuleDB.connectDB();
            Statement stmt=con.createStatement();
            ResultSet result=stmt.executeQuery(sqlHotel);
            
            nmHotel.setText(result.getString("nama_hotel"));
            alamat.setText(result.getString("alamat_hotel"));
            tingkatBintang.setText(result.getString("bintang"));
            startingPrice.setText(result.getString("starting_price"));
            fasilitas.setText(result.getString("fasilitas_hotel"));
            totalRating.setText(result.getString("rating_hotel"));
            
            String sqlRuangan= "SELECT * FROM ruangan WHERE id_hotel="+idHotel;
            ResultSet result2=stmt.executeQuery(sqlRuangan);
            DefaultTableModel model=(DefaultTableModel)jtabRuangan.getModel();
            while(result2.next()){
                Vector row=new Vector();
                row.add(result.getString("kelas_ruang"));
                row.add(result.getString("kapasitas"));
                row.add(result.getInt("harga_per_malam"));
                model.addRow(row);
            }
            jtabRuangan.setModel(model);
            
            String sqlNoTlp="SELECT * FROM no_telp WHERE status_moderasi='approved' AND id_hotel="+idHotel;
            ResultSet result3=stmt.executeQuery(sqlNoTlp);
            DefaultTableModel model2=(DefaultTableModel)jtabNoTlp.getModel();
            while(result3.next()){
                Vector row=new Vector();
                row.add(result.getString("no_telp"));
                model2.addRow(row);
            }
            jtabNoTlp.setModel(model2);
            
            String sqlReview="SELECT r.id_hotel,r.id_user,r.isi_review,u.id_user,u.nama_lengkap,h.id_hotel FROM review r, user u, hotel h WHERE r.id_user=u.id_user AND r.id_hotel=h.id_hotel AND h.id_hotel="+idHotel;
            ResultSet result4=stmt.executeQuery(sqlReview);
            DefaultTableModel model3=(DefaultTableModel)jtabTampilReview.getModel();
            while(result4.next()){
                Vector row=new Vector();
                row.add(result.getString("nama_lengkap"));
                row.add(result.getString("isi_review"));
                model3.addRow(row);
            }
            jtabTampilReview.setModel(model3);
            
            con.close();
        }
        catch(SQLException e){
            showMessageDialog(null,e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
    }
    private void cekPanelRating(){
        try{
        String sqlCek="SELECT * FROM userkasihrating WHERE id_user="+ModuleDB.id_user+" AND id_hotel="+idHotel;
        Connection con=ModuleDB.connectDB();
        Statement stmt=con.createStatement();
        ResultSet result=stmt.executeQuery(sqlCek);

        if(result.next()){
            panelNotifRanting.setVisible(true);
            panelRating.setVisible(false);
            con.close();
        }
        else{
            panelNotifRanting.setVisible(false);
            panelRating.setVisible(true);
            con.close();
        }
        
        }
        catch(SQLException e){
            showMessageDialog(null,e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void cekPanelReview(){
        try{
        String sqlCek="SELECT * FROM review WHERE id_user="+ModuleDB.id_user+" AND id_hotel="+idHotel;
        Connection con=ModuleDB.connectDB();
        Statement stmt=con.createStatement();
        ResultSet result=stmt.executeQuery(sqlCek);

        if(result.next()){
            panelNotifReview.setVisible(true);
            panelReview.setVisible(false);
            con.close();
        }
        else{
            panelNotifReview.setVisible(false);
            panelReview.setVisible(true);
            con.close();
        }
        
        }
        catch(SQLException e){
            showMessageDialog(null,e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
        
    }
//    public void tampil(){
//        String[] gambar= new String[3];
//        int[] idGambar = new int[3];
//        int count = 0;
//        panelGambar2.setLayout(new FlowLayout(FlowLayout.LEFT));
//        try{
//        
//        String sql="SELECT * from gambar WHERE id_hotel=25";
//        Connection con=ModuleDB.connectDB();
//        Statement stmt=con.createStatement();
//        ResultSet result=stmt.executeQuery(sql);
//            while(result.next() && count<3){
//                gambar[count]=result.getString("path_gambar");
//                idGambar[count]=result.getInt("id_gambar");
//                count++;
//            }
//        }
//        catch(SQLException e){
//            showMessageDialog(null,e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
//        }
//        
//        for(int i=0;i<3;i++){
//            final int c = i;
//            BufferedImage img= null;
//            try{
//                img = ImageIO.read(new File(gambar[i]));
//            } catch(IOException e){
//                showMessageDialog(null,e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
//            }
//            Image newImg = img.getScaledInstance(145, 210, Image.SCALE_SMOOTH);
//            ImageIcon imgIcon = new ImageIcon(newImg);
//           
//            panelGambar.add(new JButton("Blabla",imgIcon){
//                {
//                    setSize(145, 210);
//                    setMaximumSize(getSize());
//                    setVerticalTextPosition(SwingConstants.BOTTOM);
//                    setHorizontalTextPosition(SwingConstants.CENTER);
//                    addActionListener(new java.awt.event.ActionListener(){
//                        public void actionPerformed(java.awt.event.ActionEvent evt){
//                            btnTampilActionPerformed(evt, idGambar[c]);
//                        }
//                    });
//                }
//            });
//            System.out.println(gambar[i]);
//        }
//    }
//    private void btnTampilActionPerformed(java.awt.event.ActionEvent evt, int i){
//        System.out.println(i);//olih id
//    }
    
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setLocationRelativeTo(null);
        if("guest".equals(ModuleDB.level)){ //kalo user guest
            notif.setVisible(false);
            cekPanelRating();
            cekPanelReview();
            cekFavorite();
        } 
        else if(ModuleDB.level==null){ //kalo user biasa
           panelTambahGambar.setVisible(false);
           PanelTlp.setVisible(false);
           panelNotifRanting.setVisible(false);
           panelRating.setVisible(false);
           panelReview.setVisible(false);
           panelNotifReview.setVisible(false);
           btnTambahFavorite.setVisible(false);
           
        }
        else{ //kalo admin
            notif.setVisible(false);
            panelNotifReview.setVisible(false);
            panelNotifRanting.setVisible(false);
            cekFavorite();
        }
        tampilDetail();
        
    }//GEN-LAST:event_formWindowOpened

    private void cekFavorite(){
         try{
            Connection con=ModuleDB.connectDB();
            Statement stmt=con.createStatement();
            String sqlCek="SELECT * FROM favorite WHERE id_user="+ModuleDB.id_user+" AND id_hotel="+idHotel;
            ResultSet result=stmt.executeQuery(sqlCek);
                if(result.next()){
                    btnTambahFavorite.setVisible(false);
                }
                else
                    btnTambahFavorite.setVisible(true);
            con.close();
            
        }
        catch(SQLException e){
            showMessageDialog(null,e.getMessage(),"Error!",JOptionPane.ERROR_MESSAGE);
        }
    }
    private void btnBuatReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuatReviewActionPerformed
        String isiReview=txtIsiReview.getText();
        if (!isiReview.isEmpty()){
            try{

                Connection con=ModuleDB.connectDB();
                Statement stmt=con.createStatement();
                String sql="INSERT  INTO review (id_hotel, id_user, isi_review) VALUES('"+idHotel+"','"+ModuleDB.id_user+"','"+isiReview+"');";
                stmt.executeUpdate(sql);
                tampilDetail();
                showMessageDialog(null,"Review Berhasil Ditambahkan!");
                panelReview.setVisible(false);
                panelNotifReview.setVisible(true);
                con.close();

            }
            catch(SQLException e){
                showMessageDialog(null,e.getMessage(),"Error!",JOptionPane.ERROR_MESSAGE);
            }
        }
//        else if(kalo isinya bukan huruf !!!){
//            
//        }
        else
        showMessageDialog(null,"Semua field harus disi");
    }//GEN-LAST:event_btnBuatReviewActionPerformed

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        JFileChooser chooser = new JFileChooser(System.getProperty("user.home"));
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        chooser.setFileFilter(new FileNameExtensionFilter("jpg|png|bmp", "jpg","png","bmp"));

        if(chooser.showOpenDialog(this)==JFileChooser.APPROVE_OPTION){
            File file=chooser.getSelectedFile();
            try {
                image = ImageIO.read(file);
                panelGambar1.setImage(image);
            } catch (IOException ex) {
                Logger.getLogger(TambahHotel.class.getName()).log(Level.SEVERE, null, ex);
            }
            txtFoto.setText(file.getAbsolutePath());
        }
    }//GEN-LAST:event_btnBrowseActionPerformed

    private void txtFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFotoActionPerformed

    private void btnTambahGbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahGbrActionPerformed

        String gambar=txtFoto.getText();
        String status="waiting";
        if(!gambar.isEmpty()){
            try{
                Connection con=ModuleDB.connectDB();
                Statement stmt=con.createStatement();
                String sqlCek="Select * from gambar WHERE path_gambar='"+gambar+"' AND id_hotel="+idHotel;
                ResultSet result=stmt.executeQuery(sqlCek);
                if (!result.next()){
                    String sql="INSERT  INTO gambar ( id_hotel, id_user, path_gambar, status_moderasi) VALUES('"+idHotel+"','"+ModuleDB.id_user+"','"+gambar+"','"+status+"');";
                    stmt.executeUpdate(sql);
                    con.close();
                    showMessageDialog(null,"Gambar berhasil ditambah, menunggu moderasi dari admin !");
                    txtFoto.setText(null);
                    panelGambar1.setImage(null);
                }
                else{
                    showMessageDialog(null,"Gambar sudah ada !!!");
                    con.close();
                }
            }
            catch(SQLException e){
                showMessageDialog(null,e.getMessage(),"Error!",JOptionPane.ERROR_MESSAGE);
            }
        }
        else
        showMessageDialog(null,"Semua Field Harus diisi!");
    }//GEN-LAST:event_btnTambahGbrActionPerformed

    private void btnTambahNoTloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahNoTloActionPerformed
        String noTlp=tfNoHp.getText();
        String status="waiting";
        if(!noTlp.isEmpty()){
            try{
                Connection con=ModuleDB.connectDB();
                Statement stmt=con.createStatement();
                String sqlCek="Select * from no_telp WHERE no_telp='"+noTlp+"' AND id_hotel="+idHotel;
                ResultSet result=stmt.executeQuery(sqlCek);
                if (!result.next() && noTlp.matches("[0-9]*")){
                    String sql="INSERT  INTO no_telp ( no_telp, id_hotel, id_user, status_moderasi) VALUES('"+noTlp+"','"+idHotel+"','"+ModuleDB.id_user+"','"+status+"');";
                    stmt.executeUpdate(sql);
                    con.close();
                    showMessageDialog(null,"No Tlp berhasil ditambah, Menunggu Moderasi dari admin!");
                    tfNoHp.setText(null);
                }
                else if(!noTlp.matches("[0-9]*")){
                    showMessageDialog(null,"No Telp bukan angka !!!");
                    con.close();
                }
                else{
                    showMessageDialog(null,"No Telp sudah ada !!!");
                    con.close();
                }
            }
            catch(SQLException e){
                showMessageDialog(null,e.getMessage(),"Error!",JOptionPane.ERROR_MESSAGE);
            }
        }
        else
        showMessageDialog(null,"Semua Field Harus diisi!");
    }//GEN-LAST:event_btnTambahNoTloActionPerformed

    private void tfNoHpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNoHpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNoHpActionPerformed

    private void btnBuatRatinggActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuatRatinggActionPerformed
        String kebersihan=cbKebersihan.getSelectedItem().toString();
        String kenyamanan=cbKenyamanan.getSelectedItem().toString();
        String makanan= cbMakanan.getSelectedItem().toString();
        String ruangan= cbRuangan.getSelectedItem().toString();
        String pelayanan=cbPelayanan.getSelectedItem().toString();
        int n1 = convert(kebersihan);
        int n2 = convert(kenyamanan);
        int n3 = convert(makanan);
        int n4 = convert(ruangan); 
        int n5 = convert(pelayanan);

        double total= (n1+n2+n3+n4+n5)*1.0/5;

        try{
            Connection con=ModuleDB.connectDB();
            Statement stmt=con.createStatement();
            String ambilRatingLama="SELECT * FROM hotel WHERE id_hotel="+idHotel;
            ResultSet result=stmt.executeQuery(ambilRatingLama);
            double ratingLama=result.getInt("rating_hotel");
            
            String banyaknyaYangKasihRating="SELECT id_hotel, COUNT(id_user) FROM UserKasihRating WHERE id_hotel="+idHotel;
            ResultSet result2=stmt.executeQuery(banyaknyaYangKasihRating);
            int totalUser=result2.getInt("COUNT(id_user)"); //dapetin angka total user yang kasih, namun si user itu belum ke hitung
           
            double rataRataRating=(ratingLama+total)/(totalUser+1);
            
            String sql="UPDATE Hotel SET rating_hotel='"+rataRataRating+"' WHERE id_hotel="+idHotel;
            String sqlYangKasihRating="insert into userkasihrating (id_hotel,id_user) VALUES ('"+idHotel+"','"+ModuleDB.id_user+"');";
            stmt.executeUpdate(sql);
            stmt.executeUpdate(sqlYangKasihRating);
            tampilDetail();
            showMessageDialog(null,"Rating Berhasil Diakumulasi!");
            panelRating.setVisible(false);
            panelNotifRanting.setVisible(true);
            con.close();
            
        }
        catch(SQLException e){
            showMessageDialog(null,e.getMessage(),"Error!",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuatRatinggActionPerformed

    private void btnTambahFavoriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahFavoriteActionPerformed
         try{
            Connection con=ModuleDB.connectDB();
            Statement stmt=con.createStatement();
            String sql="insert into favorite (id_hotel,id_user) VALUES ('"+idHotel+"','"+ModuleDB.id_user+"');";
            stmt.executeUpdate(sql);
            showMessageDialog(null,"Berhasil ditambahkan ke Favorite");
            btnTambahFavorite.setVisible(false);
            con.close();
            
        }
        catch(SQLException e){
            showMessageDialog(null,e.getMessage(),"Error!",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnTambahFavoriteActionPerformed

    private int convert (String nilai){
        if(nilai=="1"){
            return 1;
        }
        if(nilai=="2"){
            return 2;
        }
        if(nilai=="3"){
            return 3;
        }
        if(nilai=="4"){
            return 4;
        }
        if(nilai=="5"){
            return 5;
        }
        if(nilai=="6"){
            return 6;
        }
        if(nilai=="7"){
            return 7;
        }
        if(nilai=="8"){
            return 8;
        }if(nilai=="9"){
            return 9;
        }
        if(nilai=="10"){
            return 10;
        }
        return -1;
    }
    
    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LihatDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LihatDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LihatDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LihatDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LihatDetail().setVisible(true);
            }
        });
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelTlp;
    private javax.swing.JLabel alamat;
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnBuatRatingg;
    private javax.swing.JButton btnBuatReview;
    private javax.swing.JButton btnTambahFavorite;
    private javax.swing.JButton btnTambahGbr;
    private javax.swing.JButton btnTambahNoTlo;
    private javax.swing.JComboBox<String> cbKebersihan;
    private javax.swing.JComboBox<String> cbKenyamanan;
    private javax.swing.JComboBox<String> cbMakanan;
    private javax.swing.JComboBox<String> cbPelayanan;
    private javax.swing.JComboBox<String> cbRuangan;
    private javax.swing.JPanel detailGambar;
    private javax.swing.JLabel fasilitas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jtabNoTlp;
    private javax.swing.JTable jtabRuangan;
    private javax.swing.JTable jtabTampilReview;
    private javax.swing.JLabel nmHotel;
    private javax.swing.JLabel notif;
    private javax.swing.JLabel notifnya;
    private javax.swing.JLabel notifnya1;
    private carihotelyuk.PanelGambar panelGambar1;
    private javax.swing.JPanel panelNotifRanting;
    private javax.swing.JPanel panelNotifReview;
    private javax.swing.JPanel panelRating;
    private javax.swing.JPanel panelReview;
    private javax.swing.JPanel panelTambahGambar;
    private javax.swing.JLabel startingPrice;
    private javax.swing.JTextField tfNoHp;
    private javax.swing.JLabel tingkatBintang;
    private javax.swing.JLabel totalRating;
    private javax.swing.JTextField txtFoto;
    private javax.swing.JTextArea txtIsiReview;
    // End of variables declaration//GEN-END:variables
}
