/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carihotelyuk;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author Katon Gilang
 */
public class Login extends javax.swing.JFrame {
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pfPass = new javax.swing.JPasswordField();
        tfUsername = new javax.swing.JTextField();
        jButtonLogin = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cbSebagai = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuBeranda = new javax.swing.JMenuItem();
        jMenuUser = new javax.swing.JMenu();
        jMenuItemDaftar = new javax.swing.JMenuItem();
        jMenuItemMasuk = new javax.swing.JMenuItem();
        jMenuTentang = new javax.swing.JMenu();
        jMenuItemPengembang = new javax.swing.JMenuItem();
        jMenuItemVersi = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Login User"));

        jLabel2.setText("Username         :");

        jLabel3.setText("Password          :");

        pfPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfPassActionPerformed(evt);
            }
        });
        pfPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pfPassKeyPressed(evt);
            }
        });

        tfUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUsernameActionPerformed(evt);
            }
        });
        tfUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfUsernameKeyPressed(evt);
            }
        });

        jButtonLogin.setText("MASUK");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });

        jLabel4.setText("Sebagai             :");

        cbSebagai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "guest", "admin" }));
        cbSebagai.setToolTipText("");
        cbSebagai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSebagaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButtonLogin)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(pfPass, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(tfUsername))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(cbSebagai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pfPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbSebagai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonLogin)
                .addGap(460, 460, 460))
        );

        jMenu1.setText("Lihat");

        menuBeranda.setText("Beranda");
        menuBeranda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBerandaActionPerformed(evt);
            }
        });
        jMenu1.add(menuBeranda);

        jMenuBar1.add(jMenu1);

        jMenuUser.setText("User");

        jMenuItemDaftar.setText("Daftar");
        jMenuItemDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDaftarActionPerformed(evt);
            }
        });
        jMenuUser.add(jMenuItemDaftar);

        jMenuItemMasuk.setText("Masuk");
        jMenuItemMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMasukActionPerformed(evt);
            }
        });
        jMenuUser.add(jMenuItemMasuk);

        jMenuBar1.add(jMenuUser);

        jMenuTentang.setText("Tentang");

        jMenuItemPengembang.setText("Pengembang");
        jMenuTentang.add(jMenuItemPengembang);

        jMenuItemVersi.setText("Versi");
        jMenuTentang.add(jMenuItemVersi);

        jMenuBar1.add(jMenuTentang);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login(){
        String username=tfUsername.getText();
        String password=pfPass.getText();
        String status=cbSebagai.getSelectedItem().toString();
        
        //enkripsi koplok :v
        char[] kr ={'0','1','2','3','4','5','6','7','8','9',' ','.','□',+
                 'a','b','c','d','e','f','g','h','i','j','k','l','m',+
                'n','o','p','q','r','s','t','u','v','w','x','y','z'};
        String userEnkrip = "";
        String passEnkrip = "";
     
        char[] cArray1 =(username).toCharArray();
        char[] cArray2 =(password).toCharArray();

        for (char c1 : cArray1){
            for(int i=0; i<=38; i++){
                if(c1 == kr[i]){
                   i = i+(Integer.parseInt("10"));
                   if(i>=39){
                       i = i-39;
                    }
                    c1 = kr[i];
                    userEnkrip = userEnkrip + c1;
                 }
            }
        }
        
        for (char c2 : cArray2){
            for(int i=0; i<=38; i++){
                if(c2 == kr[i]){
                   i = i+(Integer.parseInt("10"));
                   if(i>=39){
                       i = i-39;
                    }
                    c2 = kr[i];
                    passEnkrip = passEnkrip + c2;
                 }
            }
        }
        
        if(!username.isEmpty() && !password.isEmpty()){
            try{
                Connection con=ModuleDB.connectDB();
                String sql="SELECT * FROM User WHERE username='"+userEnkrip+"' AND password='"+passEnkrip+"'  AND level='"+status+"';";
                Statement stmt=con.createStatement();
                ResultSet result=stmt.executeQuery(sql);
                
                if (!result.next()){//kalo gak ada di database
                    showMessageDialog(null,"Username atau password salah!");
                }
                else {
                    //buat nyimpen
                    ModuleDB.id_user=result.getInt("id_user");
                    ModuleDB.username=result.getString("username");
                    ModuleDB.nama_lengkap=result.getString("nama_lengkap");
                    ModuleDB.password=result.getString("password");
                    ModuleDB.email=result.getString("email");
                    ModuleDB.level=result.getString("level");
    
                    new Home().setVisible(true); 
                    this.dispose();//menyembunyikan halaman login
                    
                
                }
                con.close();
            }
            catch(Exception e){
                showMessageDialog(null,e.getMessage(),"Error!",JOptionPane.ERROR_MESSAGE);
            }
        }
        else
            showMessageDialog(null,"Username dan password harus terisi!");
    }
   
    private void pfPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfPassActionPerformed
      
    }//GEN-LAST:event_pfPassActionPerformed

    private void tfUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUsernameActionPerformed
        // TODO add our handling code here:
    }//GEN-LAST:event_tfUsernameActionPerformed

    private void pfPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pfPassKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
            login();
        else if(evt.getKeyCode()==KeyEvent.VK_UP)
            tfUsername.requestFocus();
    }//GEN-LAST:event_pfPassKeyPressed

    private void tfUsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfUsernameKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
            login();
        else if(evt.getKeyCode()==KeyEvent.VK_DOWN)
            pfPass.requestFocus();
    }//GEN-LAST:event_tfUsernameKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowOpened

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        login();
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jMenuItemDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDaftarActionPerformed
        new Register().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItemDaftarActionPerformed

    private void jMenuItemMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMasukActionPerformed
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItemMasukActionPerformed

    private void menuBerandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBerandaActionPerformed
        new Home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuBerandaActionPerformed

    private void cbSebagaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSebagaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSebagaiActionPerformed
   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbSebagai;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemDaftar;
    private javax.swing.JMenuItem jMenuItemMasuk;
    private javax.swing.JMenuItem jMenuItemPengembang;
    private javax.swing.JMenuItem jMenuItemVersi;
    private javax.swing.JMenu jMenuTentang;
    private javax.swing.JMenu jMenuUser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem menuBeranda;
    private javax.swing.JPasswordField pfPass;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
