/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carihotelyuk;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Katon Gilang
 */
public class ModerasiNoTlp extends javax.swing.JFrame {

    /**
     * Creates new form ModerasiNoTlp
     */
    public ModerasiNoTlp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtabDaftarModerasiNoTlp = new javax.swing.JTable();
        buttonSetuju = new javax.swing.JButton();
        buttonDelete = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jtabDaftarModerasiNoTlp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No Tlp", "Nama Hotel", "Nama Lengkap", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtabDaftarModerasiNoTlp);

        buttonSetuju.setText("Setujui");
        buttonSetuju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSetujuActionPerformed(evt);
            }
        });

        buttonDelete.setText("Tolak");
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });

        jLabel1.setText("DAFTAR NO TLP YANG MENUNGGU MODERASI");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSetuju)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSetuju)
                    .addComponent(buttonDelete))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void daftarNoTlp(){
        try{
            String sql = "SELECT n.no_telp,n.id_user,n.id_hotel,n.status_moderasi,h.id_hotel,h.nama_hotel,u.id_user,u.nama_lengkap FROM hotel h, no_telp n, user u WHERE n.status_moderasi='waiting' AND n.id_hotel=h.id_hotel AND n.id_user=u.id_user";
            Connection con=ModuleDB.connectDB();
            Statement stmt=con.createStatement();
            ResultSet result=stmt.executeQuery(sql);
            DefaultTableModel model=(DefaultTableModel)jtabDaftarModerasiNoTlp.getModel();
            model.setRowCount(0);
            while(result.next()){
                Vector row=new Vector();
                row.add(result.getString("no_telp"));
                row.add(result.getString("nama_hotel"));                
                row.add(result.getString("nama_lengkap"));
                row.add(result.getString("status_moderasi"));
                model.addRow(row);
            }
            con.close();
            jtabDaftarModerasiNoTlp.setModel(model);
        }
        catch(SQLException e){
            showMessageDialog(null,e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setLocationRelativeTo(null);
        daftarNoTlp();
    }//GEN-LAST:event_formWindowOpened

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        int dialogResult=JOptionPane.showOptionDialog(null,"Apakah anda yakin ingin menolak No Tlp untuk hotel ini?","Konfirmasi Tolak dan Otomatis terhapus Data Hotel",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,null,null);
        if(dialogResult==JOptionPane.YES_OPTION){
            int rowIdx=jtabDaftarModerasiNoTlp.getSelectedRow();
            String no_telp=jtabDaftarModerasiNoTlp.getValueAt(rowIdx,0).toString();
            System.out.println(no_telp);
            try{
                String sql="DELETE FROM no_telp WHERE no_telp='"+no_telp+"'";
                Connection con=ModuleDB.connectDB();
                Statement stmt=con.createStatement();
                stmt.executeUpdate(sql);
                showMessageDialog(null,"No Tlp telah ditolak!");
                daftarNoTlp();
                con.close();
            }
            catch(SQLException e){
                showMessageDialog(null,e.getMessage());
            }
        }
    }//GEN-LAST:event_buttonDeleteActionPerformed

    private void buttonSetujuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSetujuActionPerformed
        int rowIdx=jtabDaftarModerasiNoTlp.getSelectedRow();
        String no_telp=jtabDaftarModerasiNoTlp.getValueAt(rowIdx,0).toString();
        String status= "approved";
        try{
            Connection con=ModuleDB.connectDB();
            Statement stmt=con.createStatement();
            String sql="UPDATE no_telp SET status_moderasi='"+status+"' WHERE no_telp='"+no_telp+"'";
            stmt.executeUpdate(sql);
            showMessageDialog(null,"No Tlp telah di APPROVE!");
            daftarNoTlp();
            con.close();
            
        }
        catch(SQLException e){
            showMessageDialog(null,e.getMessage(),"Error!",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonSetujuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModerasiNoTlp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModerasiNoTlp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModerasiNoTlp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModerasiNoTlp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModerasiNoTlp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton buttonDelete;
    private javax.swing.JButton buttonSetuju;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtabDaftarModerasiNoTlp;
    // End of variables declaration//GEN-END:variables
}
