/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carihotelyuk;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author Katon Gilang
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pfPass = new javax.swing.JPasswordField();
        tfUsername = new javax.swing.JTextField();
        jButtonRegister = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        pfRePass = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        tfNamaLengkap = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuBeranda = new javax.swing.JMenuItem();
        jMenuUser = new javax.swing.JMenu();
        jMenuItemDaftar = new javax.swing.JMenuItem();
        jMenuItemMasuk = new javax.swing.JMenuItem();
        jMenuTentang = new javax.swing.JMenu();
        jMenuItemPengembang = new javax.swing.JMenuItem();
        jMenuItemVersi = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Form Daftar"));

        jLabel2.setText("Username              :");

        jLabel3.setText("Password               :");

        pfPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfPassActionPerformed(evt);
            }
        });
        pfPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pfPassKeyPressed(evt);
            }
        });

        tfUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUsernameActionPerformed(evt);
            }
        });
        tfUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfUsernameKeyPressed(evt);
            }
        });

        jButtonRegister.setText("Daftar");
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });

        jLabel4.setText("Re-type Password  :");

        pfRePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfRePassActionPerformed(evt);
            }
        });
        pfRePass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pfRePassKeyPressed(evt);
            }
        });

        jLabel5.setText("Nama Lengkap       :");

        tfNamaLengkap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNamaLengkapActionPerformed(evt);
            }
        });
        tfNamaLengkap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfNamaLengkapKeyPressed(evt);
            }
        });

        tfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEmailActionPerformed(evt);
            }
        });
        tfEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfEmailKeyPressed(evt);
            }
        });

        jLabel6.setText("Email                      :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfNamaLengkap, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addComponent(pfPass, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pfRePass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonRegister, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfNamaLengkap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pfPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pfRePass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jButtonRegister)
                .addGap(22, 22, 22))
        );

        jMenuBar1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jMenu1.setText("Lihat");

        menuBeranda.setText("Beranda");
        menuBeranda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBerandaActionPerformed(evt);
            }
        });
        jMenu1.add(menuBeranda);

        jMenuBar1.add(jMenu1);

        jMenuUser.setText("User");

        jMenuItemDaftar.setText("Daftar");
        jMenuItemDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDaftarActionPerformed(evt);
            }
        });
        jMenuUser.add(jMenuItemDaftar);

        jMenuItemMasuk.setText("Masuk");
        jMenuItemMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMasukActionPerformed(evt);
            }
        });
        jMenuUser.add(jMenuItemMasuk);

        jMenuBar1.add(jMenuUser);

        jMenuTentang.setText("Tentang");

        jMenuItemPengembang.setText("Pengembang");
        jMenuTentang.add(jMenuItemPengembang);

        jMenuItemVersi.setText("Versi");
        jMenuTentang.add(jMenuItemVersi);

        jMenuBar1.add(jMenuTentang);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void register(){
        String username=tfUsername.getText();
        String nama_lengkap=tfNamaLengkap.getText();
        String email=tfEmail.getText();
        String password=String.valueOf(pfPass.getPassword());
        String RePass=String.valueOf(pfRePass.getPassword());
        String guest="guest";
        
        
        //enkripsi koplok :v
        char[] kr ={'0','1','2','3','4','5','6','7','8','9',' ','.','□',+
                 'a','b','c','d','e','f','g','h','i','j','k','l','m',+
                'n','o','p','q','r','s','t','u','v','w','x','y','z'};
        String userEnkrip = "";
        String passEnkrip = "";
     
        char[] cArray1 =(username).toCharArray();
        char[] cArray2 =(password).toCharArray();

        for (char c1 : cArray1){
            for(int i=0; i<=38; i++){
                if(c1 == kr[i]){
                   i = i+(Integer.parseInt("10"));
                   if(i>=39){
                       i = i-39;
                    }
                    c1 = kr[i];
                    userEnkrip = userEnkrip + c1;
                 }
            }
        }
        
        for (char c2 : cArray2){
            for(int i=0; i<=38; i++){
                if(c2 == kr[i]){
                   i = i+(Integer.parseInt("10"));
                   if(i>=39){
                       i = i-39;
                    }
                    c2 = kr[i];
                    passEnkrip = passEnkrip + c2;
                 }
            }
        }
        if(username.length()>=3 && nama_lengkap.length()>=3 && password.length()>=6 && password.equals(RePass)){
            
            try{
                Connection con=ModuleDB.connectDB();
                Statement stmt=con.createStatement();
                String sqlCek="SELECT * FROM User WHERE username='"+userEnkrip+"';";
                ResultSet result=stmt.executeQuery(sqlCek);
                
                if (!result.next()){
                    String sql="INSERT  INTO user (username,nama_lengkap,password,email,level) VALUES('"+userEnkrip+"','"+nama_lengkap+"','"+passEnkrip+"','"+email+"','"+guest+"');";
                    stmt.executeUpdate(sql);
                    showMessageDialog(null,"User berhasil dibuat!");
                    con.close();
                    new Login().setVisible(true);
                    this.dispose();
                    
                }
                else{
                    showMessageDialog(null,"Username sudah ada !!!");
                    con.close();
                }
                
            }
            catch(SQLException e){
                showMessageDialog(null,e.getMessage(),"Error!",JOptionPane.ERROR_MESSAGE);
            }
        }
        
        else if(username.length()<3)
            showMessageDialog(null,"Username tidak boleh kurang dari 3 karakter!");
        else if(nama_lengkap.length()<3)
            showMessageDialog(null,"Nama tidak boleh kurang dari 3 karakter");
        //else if(email.length()<6)
            //showMessageDialog(null,"Email harus sesuai format!");
        else if(password.length()<6)
            showMessageDialog(null,"Password minimal 6 karakter!");
        else if(!password.equals(RePass))
            showMessageDialog(null,"Password dan confirm password tidak cocok!");
        else showMessageDialog(null,"field tidak boleh kosong!");
    }
    private void pfPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfPassActionPerformed

    private void tfUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUsernameActionPerformed

    private void pfRePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfRePassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfRePassActionPerformed

    private void tfNamaLengkapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNamaLengkapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNamaLengkapActionPerformed

    private void tfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEmailActionPerformed

    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed
        register();
 
    }//GEN-LAST:event_jButtonRegisterActionPerformed

    private void tfUsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfUsernameKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_DOWN)
            tfNamaLengkap.requestFocus();
        else if(evt.getKeyCode()==KeyEvent.VK_ENTER)
            register();
    }//GEN-LAST:event_tfUsernameKeyPressed

    private void tfNamaLengkapKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNamaLengkapKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_UP)
            tfUsername.requestFocus();
        else if(evt.getKeyCode()==KeyEvent.VK_DOWN)
            tfEmail.requestFocus();
        else if(evt.getKeyCode()==KeyEvent.VK_ENTER)
            register();
    }//GEN-LAST:event_tfNamaLengkapKeyPressed

    private void tfEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfEmailKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_UP)
            tfNamaLengkap.requestFocus();
        else if(evt.getKeyCode()==KeyEvent.VK_DOWN)
            pfPass.requestFocus();
        else if(evt.getKeyCode()==KeyEvent.VK_ENTER)
            register();
    }//GEN-LAST:event_tfEmailKeyPressed

    private void pfPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pfPassKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_UP)
            tfEmail.requestFocus();
        else if(evt.getKeyCode()==KeyEvent.VK_DOWN)
            pfRePass.requestFocus();
        else if(evt.getKeyCode()==KeyEvent.VK_ENTER)
            register();
    }//GEN-LAST:event_pfPassKeyPressed

    private void pfRePassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pfRePassKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_UP)
            pfPass.requestFocus();
        else if(evt.getKeyCode()==KeyEvent.VK_ENTER)
            register();
    }//GEN-LAST:event_pfRePassKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowOpened

    private void jMenuItemDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDaftarActionPerformed
        new Register().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItemDaftarActionPerformed

    private void jMenuItemMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMasukActionPerformed
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItemMasukActionPerformed

    private void menuBerandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBerandaActionPerformed
        new Home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuBerandaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemDaftar;
    private javax.swing.JMenuItem jMenuItemMasuk;
    private javax.swing.JMenuItem jMenuItemPengembang;
    private javax.swing.JMenuItem jMenuItemVersi;
    private javax.swing.JMenu jMenuTentang;
    private javax.swing.JMenu jMenuUser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem menuBeranda;
    private javax.swing.JPasswordField pfPass;
    private javax.swing.JPasswordField pfRePass;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfNamaLengkap;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
